# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-12 08:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20170110_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2017, 1, 12, 8, 48, 3, 392785, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
